# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  - board: nice_nano_v2
#    shield: microdox_left
#  - board: nice_nano_v2
#    shield: microdox_right
#  - board: nice_nano_v2
#    shield: qaz
#  - board: nice_nano_v2
#    shield: rollow_left
#  - board: nice_nano_v2
#    shield: rollow_right
#  - board: technikable
#  - board: nice_nano_v2
#    shield: chocv
#  - board: nice_nano_v2
#    shield: swweeep_left
#  - board: nice_nano_v2
#    shield: swweeep_right
#  - board: adafruit_kb2040
#    shield: aaplus_v2
#  - board: seeeduino_xiao_ble
#    shield: tri_artsey
#  - board: nice_nano_v2
#    shield: naked36
#  - board: adafruit_kb2040
#    shield: lilfoot
#  - board: adafruit_kb2040
#    shield: claudia
#  - board: boardsource_blok
#    shield: dogtag
#  - board: seeeduino_xiao_ble
#    shield: pandy
#  - board: seeeduino_xiao_ble
#    shield: grumpy
  - board: seeeduino_xiao_ble
    shield: settings_reset
#  - board: nice_nano_v2
#    shield: settings_reset