file_format: "1"
id: lilfoot
name: JHL-lilfoot
type: shield
url: https://github.com/The-Royal/The_Royal_Open-Source-Projects/tree/master/01%20-%20Complete%20Kits/The_Little_Foot-Keyboard-rev2.3
requires: [pro_micro]
features:
  - keys
